### ISSUE TITLE
Sorry to bother you, this is just a question born out of pure admiration ...

### ISSUE THREAD

**Issue by jcutlerbiostats** [JohnCoene/bibler#4]
This is simply amazing. I was wondering, how did you get the Greek and Hebrew symbols/letters to play well in R?? I've never seen anything like this. It's really quite surreal seeing actual Hebrew and Greek letters in RStudio. 

I would love to know how to type these words in R so I can find/count/analyze/etc. specific Hebrew or Greek words. Is this possible? Also, do you know anything about stemming or lemmatizing with these texts?

**Comment by JohnCoene** [comment]
As you might be able to tell by the commit history, it's a very old package I haven't played with in a long time.

All the data is in the `data-raw` directory, along with the scripts to prepare the final output, namely `rawtoclean.R`.

The greek text is [here](https://raw.githubusercontent.com/JohnCoene/sacred/master/data-raw/ugntdat.txt) and I simply read it with `readLines(path, encoding = "UTF-8")`.

I hope this helps.

When it comes to analysing such text I'd go with {tidytext} nowadays. Far from knowledgeable on the topic but as far as I know as long as a word is separated by spaces/punctuation it works with most frameworks, other languages can be more difficult to deal with.

**Comment by jcutlerbiostats** [comment]
This is really cool. Thank you for the timely response. I’m just thinking
it would be a potentially novel thing to do stylometry on the Greek and
Hebrew text itself. It’s great to know how easy it was to read the text
from the internet in the first place!
Thanks for doing this!

James

**Comment by jcutlerbiostats** [comment]
Thanks!
